### ISSUE TITLE
Easy way to remove non-alphanumeric values from a variable

### ISSUE THREAD

**Issue by FunkyLoveCow** [cookiecutter/cookiecutter#1161]
* Cookiecutter version: 1.6.0
* Template project url: None
* Python version: 3.6.7
* Operating System: Ubuntu 18.04.2 LTS

### Description:

I am using the example provided in [Tutorial 1](https://cookiecutter.readthedocs.io/en/latest/tutorial1.html?#cookiecutter-json) to generate a  slug.

```
"slug": "{{ cookiecutter.project_name.lower().replace(' ', '_') }}",
```

The issue I am having is that I'd like to extend this to removing all non-alphanumeric values (ie. I don't want any punctuation in the slug).

I can do this using a regular expression, but that needs the `re` module imported.

I thought of doing a pre-hook to change the values, but I believe [this issue](https://github.com/audreyr/cookiecutter/issues/851) is telling me I can't do that.

What's the best way to extend this to do more filtering and more specifically, not allow punctuation?

**Comment by hackebrot** [comment]
Hi @FunkyLoveCow! 👋 

You might be able to use a jinja2 extension for that. There's an example for loading extensions in the [advanced usage documentation](https://cookiecutter.readthedocs.io/en/latest/advanced/template_extensions.html). 📝 

I personally do validation in the `pre_gen_project` hook rather than on the CLI prompts. See https://github.com/pytest-dev/cookiecutter-pytest-plugin/blob/master/hooks/pre_gen_project.py
