### ISSUE TITLE
Support for renaming the cookiecutter dict

### ISSUE THREAD

**Issue by trondhindenes** [cookiecutter/cookiecutter#1166]
### Description:
Is there any support for renaming the cookiecutter object to something shorter? I'm finding `cookiecutter` to be one of those words that are hard to type, and would like to use something like `cc` in Jinja templates instead

**Comment by hackebrot** [comment]
@Granitosaurus, this is your first and last warning about [Code of Conduct][code-of-conduct] violations against other contributors to Cookiecutter. ⚠️

The item of the Code of Conduct you are specifically violating is:

- [Trolling or insulting/derogatory comments][code-of-conduct item]

A sample of your insulting/derogatory writing (screen captured) from this comment thread and your pull-request (#1242):

> It's absolutely mindboggling how this project survived so long with such an absurd gap in basic UX. 

> what the hell is this?

> alias "cc" to "cookiecutter" for templating and user's sanity

Any future violations will result in an immediate banning from this project. While we encourage debate, we refuse to condone this kind of ongoing abusive behavior. We wouldn't allow this kind of treatment as paid employees, and we certainly won't take it as volunteers for an unpaid project.

[code-of-conduct]: https://github.com/cookiecutter/cookiecutter/blob/master/CODE_OF_CONDUCT.md
[code-of-conduct item]: https://www.pypa.io/en/latest/code-of-conduct/

**Comment by Granitosaurus** [comment]
@hackebrot I might have been a bit rough with my wording sorry. Been working on updating two huge cookiecutter templates and I guess typing cookiecutter a million times blew some of my sanity off lol. 

For real though, someone should look into merging my PR eitherway.

**Comment by wadkar** [comment]
Personally, I am not worried about typing `cookiecutter` because you one reads a variable an order of magnitude more than one writes. Perhaps `explicit is better than implicit` can be considered useful here?

Not to disregard any usability concerns, I do like the third option suggested earlier, i.e.  `{{foo}}.{{bar}}` though I am not sure how it can be achieved without [surprising the user too much](https://en.wikipedia.org/wiki/Principle_of_least_astonishment).

As it stands, I don't mind the status-quo and use the cookiecutter variable in jinja2 template. As for providing a shorter alias or renaming, wouldn't something like `{%- cc = cookiecutter -%}` at the beginning of template work for those who want shorter/cryptic name?

**Comment by Granitosaurus** [comment]
I've been using `cc` alias from the MR since I posted the merge request and never looked back.

>  Perhaps `explicit is better than implicit` can be considered useful here?  

I'm having trouble imagining where explicit `cookiecutter` would yield any benefits over short alias such as `cc`  

> wouldn't something like {%- cc = cookiecutter -%} at the beginning of template work for those who want shorter/cryptic name?

Including a line in every file is a bit silly.

Personally I disagree with you — it's a very easy issue. Just give people few options, long name + short name, it has nothing to do with naming it's a simple pragmatic issue, typing 12 characters vs typing 2 over and over again is a no brainer issue IMHO.

**Comment by wadkar** [comment]
> I'm having trouble imagining where explicit `cookiecutter` would yield any benefits over short alias such as `cc`

The benefit is that the reader does _not_ have to mentally translate the `cc` alias to `cookiecutter`. I can't speak to your imagination but it could be possible that you have internalized `cc = cookiecutter` and probably have written few templates with it. So perhaps you don't see any difference between `cc` and `cookiecutter`.

Contributors like me, however, have to read a template or two over and over again because we need to debug it and provide a PR/bugfix. A template gets written once, but gets at least few multiples of PRs for feature/bugfixes.

> > wouldn't something like {%- cc = cookiecutter -%} at the beginning of template work for those who want shorter/cryptic name?
> 
> Including a line in every file is a bit silly.

Agreed, better use `cookiecutter` everywhere, if you ask me.

> Personally I disagree with you — it's a very easy issue. Just give people few options, long name + short name, it has nothing to do with naming it's a simple pragmatic issue, typing 13 characters vs typing 2 over and over again is a no brainer issue IMHO.

Okay, about options, can you please tell me why `cc`? Why not `ck` as short for cookie, or `cut` or `cct` or something else? How do we decide which keyword is better option?

**Comment by Granitosaurus** [comment]
@wadkar sorry I can't really follow you. How do you even make out such a simple issue as additional alias so complicated. How could anyone have trouble reading `cc` instead of `cookiecutter`.   
You can close this issue and my PR for all I care, I raised my proposal and clearly there's nothing of value to discuss here. 

For those who want the alias I'm maintaining a fork and pypi repo:

https://github.com/Granitosaurus/cookiecutter-cc
https://pypi.org/project/cookiecutter-cc/

bye.

**Comment by brempusz** [comment]
My first impression with cookiecutter was: why do I even need this prefix? I would like to use `{{myVariable}}` instead of `{{cookiecutter.myVariable}}`.  
Then I checked the docs to see if its possible to change `cookiecutter` to something shorter and more descriptive, like `vars` or `cfg`. 
Then I just accepted the way it was implemented...

So I guess adding option to rename the prefix would be sweet spot - if you have problem with short name, just use default.

**Comment by wadkar** [comment]
@brempusz I believe that's what #1233 hopes to do. Though I am not sure if it's being discussed currently in this issue as opposed #1244 .

@Granitosaurus Huh? I am not a contributor or the maintainer for the project who can close the issue (you can, of course). I am just a user providing my perspective. I am really baffled as to why you're attacking and being hostile towards me. This is quite unlike the typical interaction I have had within the python community.

As I mentioned in my first comment, I want to hear what the maintainers and other developers/users have to say about this. If you think that is not a valuable discussion, sure go ahead and maintain your own acerbic fork.

**Comment by insspb** [comment]
@wadkar @brempusz @Granitosaurus @hackebrot @trondhindenes 

I am thinking about this issue for a while, when was worked on 1.7.x

Many PRs related to namespace variables, and I am inviting all their contributors here for discussion.

Related issues and PRs: 

* #380 - Remove cookiecutter namespace discussion
* #822 - Custom context template holder name
* #1166 - Renaming cookiecutter dictionary
* #1233 - Parametrize namespace
* #1242 - Alias "cc" to "cookiecutter"
* #1244 - Alias "cc" to "cookiecutter"

My main concern is that namespace cli or class setting has no sense. This option will require user to write `cookiecutter --namespace=cc` or something like this, just to make some template work on their side. Or will require us to hardcode some value in our internals, as 'cookiecutter' now.

As I see it now: Correct solution is to implement namespace naming based on raw variable in template. Like it done with [`_copy_without_render`](https://cookiecutter.readthedocs.io/en/latest/advanced/copy_without_render.html) or [`_new_lines`](https://cookiecutter.readthedocs.io/en/latest/advanced/new_line_characters.html)

So we need to implement `_namespace` inside template, and check it in mentioned `cookiecutter/cookiecutter/generate.py` and pass it in next stages as independent variable.

I will do it myself before 2.0 if nobody will not be able to do it before, but this implementation is another way of hardcodding, that should be avoided.

I propose to make any further discussion in original issue #380

This issue is closed, to keep all discussion in #380. 

I am inviting all to join.
