### ISSUE TITLE
[Feature Request] Add a command-line parameter so cookiecutter just replace the cached cookiecutter repository

### ISSUE THREAD

**Issue by nieltg** [cookiecutter/cookiecutter#1201]
* Cookiecutter version: 1.6.0
* Template project url: None
* Python version: 3.7
* Operating System: macOS

### Description:

I'm proposing a feature here to add a command-line parameter, so cookiecutter will automatically update the cached cookiecutter repository.

So, we can enforce everyone to have the cookiecutter repository updated.

#### Previously

Cookiecutter will ask whether to update the cache or not.

```
$ cookiecutter [REPO]
You've downloaded /home/nieltg/.cookiecutters/skeleton-ruby before. Is it okay to delete and re-download it? [yes]: 
Enter passphrase for key '/home/nieltg/.ssh/id_rsa': 
```

#### Proposed

We can put a command-line parameter so cookiecutter just updates the cache.

```
$ cookiecutter --refresh [REPO]
Enter passphrase for key '/home/nieltg/.ssh/id_rsa': 
```

Thank you very much!
If that's possible, I'm willing to make a pull request in my free time.

**Comment by svermeulen** [comment]
Yes I find this prompt annoying every time I use cookiecutter with a URL.  I would much prefer that it use the cache by default unless it gets over-ridden with `--refresh`

**Comment by svermeulen** [comment]
I have also discovered this bug:  https://github.com/cookiecutter/cookiecutter/issues/1082 which means that the only reliable way to use cookie cutter with a git URL + branch is to _always_ re-download (since the cache does not index by branch and only URL).  So a setting to enforce this behaviour every time would be great to avoid getting bitten by #1082

**Comment by glumia** [comment]
If I understand correctly, the rationale for @nieltg to add this feature is *"don't bother asking me whether to use the cached version of the template or not, just refresh it"* (`--refresh` option), while @svermeulen's one is the complementary *"don't bother asking me whether to use the cached version of the template or not, just use it"* (a new default in case of missing `--refresh`).

Those seem to me a bit weak as reasons to introduce a new feature and a breaking change.

Regarding the new feature, the only good reason to introduce something like that is in case someone needs to totally disable user input (eg. cookiecutter used in shell scripts) but this is already possible with the `--no-input` flag (cookiecutter in this case refreshes cache's content); otherwise it's just an additional `Enter` keypress. 

Regarding the new default, even if I could agree with the prompt being annoying in case one wants to use the cached version, it's certainly not a good reason to break retro compatibility. Maybe we could add a new setting for that to [user config](https://cookiecutter.readthedocs.io/en/1.7.2/advanced/user_config.html?highlight=config#) (@svermeulen feel free to open an issue/pull request for that, it's a feature I would certainly welcome).

For what concerns #1082, adding a feature as a workaround for a bug is wrong in many ways and it's a something we need to avoid at all costs if we don't want cookiecutter to collapse on itself in the long run.

**Comment by justinessert** [comment]
@glumia could you help me understand why this would be a breaking change?

It would just be creating a new flag/arg that has a default value (ie. in [1540](https://github.com/cookiecutter/cookiecutter/pull/1540) it was implemented without the need to change a single test). How would this affect any users’ ability to use cookiecutter?

**Comment by glumia** [comment]
The new `--refresh` flag as implemented in #1540 isn't a breaking change, it is the request to use the cached template by default if this option is not provided.

But even so, it would remain a feature that overlaps with what is already provided by the `--no-input` option.

**Comment by justinessert** [comment]
@glumia The `--refresh` flag does provide unique functionality. Although admittedly not necessary, it can help improve the user experience of `cookiecutter`.

For example, I have a use case where I (a more technical person) am setting up a cookie cutter template for others (less technical people) to use. I give them the CLI command to use (or rather wrap the command in a shell script) and they will each need to fill in their own details (ie. `--no-input` is not an option), and having the `Is it okay to delete and re-download it?` message just provides another opportunity to confuse people.

**Comment by SharpEdgeMarshall** [comment]
@justinessert even if I completely understand your use case, the way is proposed and implemented looks like a `--no-input` just for cache.
IMO we should at least find a better keyword.

**Comment by glumia** [comment]
But in this case, it would be sufficient to provide the following command to those less technical people (suppose the template is `cookiecutter-pypackage`):  
```shell
rm -rf ~/.cookiecutters/cookiecutter-pypackage && cookiecutter gh:audreyfeldroy/cookiecutter-pypackage
```

Is it really worth maintaining a new feature just to not use this compound command? 

Do not underestimate the maintenance effort: it is true that the implementation is trivial and that it has some value (`cookiecutter --refresh gh:audreyfeldroy/cookiecutter-pypackage` is definitely prettier than the command above) but after that it's added we would have to take care of it *forever*. Breaking retro compatibility is way worse than not providing a feature in the first place. And think of what happens when 'smaller features' like this one are added one after the other: in no time you find yourself with an enormous codebase where even the smallest change is expensive.

You can ask other mantainers a feedback if you don't agree, but in my opinion this feature is not worth it.

PS: Please don't take it personally, I'm really sorry to block this request but it's to prevent cookiecutter from growing indefinitely!

**Comment by levilime** [comment]
While using cookiecutter automatically through an external script with `--no-input` I had been quite confused why my templates did not reflect the changes I made on my cookiecutter template in the repo. A `--no-input-no-cache` option would be nice, but just removing the local cache as suggested:

> But in this case, it would be sufficient to provide the following command to those less technical people (suppose the template is `cookiecutter-pypackage`):
> 
> ```shell
> rm -rf ~/.cookiecutters/cookiecutter-pypackage && cookiecutter gh:audreyfeldroy/cookiecutter-pypackage
> ```
> 
> Is it really worth maintaining a new feature just to not use this compound command?
> 
> Do not underestimate the maintenance effort: it is true that the implementation is trivial and that it has some value (`cookiecutter --refresh gh:audreyfeldroy/cookiecutter-pypackage` is definitely prettier than the command above) but after that it's added we would have to take care of it _forever_. Breaking retro compatibility is way worse than not providing a feature in the first place. And think of what happens when 'smaller features' like this one are added one after the other: in no time you find yourself with an enormous codebase where even the smallest change is expensive.
> 
> So, in my opinion, this feature is not worth it. (you can ask other maintainers a feedback if you don't agree)
> 
> PS: Please don't take it personally, I'm really sorry to block this request but it's to prevent cookiecutter from growing indefinitely!

works for my purposes.
Thanks!
