### ISSUE TITLE
Where to put Jinja extension code?

### ISSUE THREAD

**Issue by pouledodue** [cookiecutter/cookiecutter#1211]
Hi
I put extension code in `cookiecutter.json`
```
{
"_extensions": ["super.SuperExtension"]
}
```

and I created the `super/super.py` and `super/__init__.py` files with:
```
from jinja2 import nodes
from jinja2.ext import Extension


class SuperExtension(Extension):
    # a set of names that trigger the extension.
    # tags = {'cache'}

    def __init__(self, environment):
        super(SuperExtension, self).__init__(environment)

        # add the defaults to the environment
        environment.extend(
            keep_trailing_newline=True
        )
```

However when I run the cookiecutter command it keeps telling me 
`cookiecutter.exceptions.UnknownExtension: Unable to load extension: No module named 'super'`

I copied the `super` directory everywhere I can think and it don't find it.
So my question is where do I need to put the `super` dir?

**Comment by pydanny** [comment]
Super is a reserved python keyword. Try a different module name.

**Comment by pouledodue** [comment]
Hi
I renamed all to `hello` and `hello.HelloExtension` yet I have the same error:
`ModuleNotFoundError: No module named 'hello'`

Where do I put the `hello` dir?

**Comment by michaeljoseph** [comment]
@pouledodue you need to put the `hello` directory on your `PYTHONPATH`.

<img width="799" alt="image" src="https://user-images.githubusercontent.com/169933/63210202-bcdda280-c0eb-11e9-825f-e12deda415d1.png">

**Comment by michaeljoseph** [comment]
An improvement to the [docs](https://cookiecutter.readthedocs.io/en/latest/advanced/template_extensions.html) would be appreciated 📖 ✍️ 🙏

**Comment by pouledodue** [comment]
thanks

**Comment by con-f-use** [comment]
Just a quick related question

Why is it, that the cookiecutter template directory is not added to path by default or at least an `extensions` directory therein? Lets say we have this structure and I have a custom extension in `my_custom_ext.py`, that I'd like to use.

```
$ tree .
.
├── cookiecutter.json
├── {{cookiecutter.package_name}}
│   └── ...
├── extensions
│   └── my_cumstom_ext.py
└── hooks
    ├── post_gen_project.py
    └── pre_gen_project.py

$ cat cookiecutter.json
{
    "_extensions": ["extensions.my_custom_ext"]
}
```

I don't want to tell my user to `export PYTHONPATH=/path/to/./extensions` or some such.
I would expect that do work out of the box. Especially not if the template is in a git repository and the user would have to figure out the `/path/to/./` part themselves.

The reason can't be security because hooks basically already allow code execution.
It can't be a maintenance burden on the cookiecutter team, because only advanced users would write their own extensions and they'd expect that they are responsible for them.

**Comment by vstepanov** [comment]
if I don't run cookiecutter yet after its installation or remove `~/.cookiecutters/my-template/` and run `PYTHONPATH=~/.cookiecutters/my-template/ cookiecutter https://github.com/.../my-template` it is failing with
`Unable to load extension: No module named 'extensions'`.
For each next run it works fine and extensions can be imported. 
Any thoughts?

**Comment by xmnlab** [comment]
as a workaround we can use`python -m cookiecutter`, for example `python -m cookiecutter --output-dir /tmp/ --no-input .`
