### ISSUE TITLE
Sort all existing PRs and issues between new projects.

### ISSUE THREAD

**Issue by insspb** [cookiecutter/cookiecutter#1258]
* PRs with no code change goes to 1.7.0 release project. Documentation/tests changes can be approved.
* PRs with code changes, but for old system goes to 1.8.0 release. 
* Huge code change proposals goes to 2.0.0. for discussion/validation.

* Outdated/Not related issues should be closed.

**Comment by ssbarnea** [comment]
The initiative to do some organization on PRs and issue is a very good one, especially as the piles did grow too much. I still have few remarks to add:

* labels should not be used for marking versions, for these project and even better the milestones are more appropriate. The main reason for this is the labels cannot be closed, the pipe-up, and after lots of releases you end-up with label-spam
* use of projects is ok for coordinating longer team goals and endeavors, ones that could spread across multiple releases. For example projects can spread across multiple repositories.
* `milestones` are optimal as they have a small footprint, aimed exactly at the release process. The only downside of milestones is that their tab is listed under issues instead of being top level tab as the projects.
* Projects can also be disabled per repository, which can be used to avoid confusions between use of projects and milestones. Milestones cannot be disabled.

If we look at [historical usage of milestones on cookiecutter ](https://github.com/cookiecutter/cookiecutter/milestones?state=closed)we see that it has 25 milestones and most of them are versions, dating back to 2014.

On the other hand, there are only 5 projects listed and all of them are recent https://github.com/cookiecutter/cookiecutter/projects

If we had being talking about a project with a permanent development team that does scrum or kanban, probably use of projects would have made sense. Still, for a project like cookiecutter which is in maintenance mode, I think that projects are less appropriate.

The good part is that if we decide to stop using projects it can be very easy to switch to milestones without loosing metadata.

**Comment by ssbarnea** [comment]
There is also another aspect which needs to be clarified: who can decide what goes into a release or gets pushed to another one? 

For example, I do not find reasonable to delay any hotfix-release for almost 4 months because some changes related to [adoption of PEP257](https://github.com/cookiecutter/cookiecutter/projects/4) where not implemented yet, especially as both of these where marked with "please-help" label. If nobody is working on them it is unlikely that they will ever be implemented and it is not ok to delay a release for these reasons. I even got the impression that these are used as ransom for "motivating" others to fix them before allowing a new release.

IMHO, we should include issues/PRs that are actively worked on a next-release, as we have no guarantee that they will be implemented or not. In most cases it is perfectly fine to wait 1-2 weeks for them to be implemented/fixed but of no progress is seen, they should just slip until someone does them.
