### ISSUE TITLE
Is it possible to only prompt for None/empty values?

### ISSUE THREAD

**Issue by dougthor42** [cookiecutter/cookiecutter#1433]
* Cookiecutter version: 1.7.0
* Template project url: N/A
* Python version: 3.6.8
* Operating System: Linux (WSL on Win10)

### Description:

I want to prompt the user for inputs only if the value (from the defaults in `cookiecutter.json` or passed in via `extra_context`) is `None` or the empty string `""`. Is this currently possible? Thus far I've only found out how to [suppress all prompts](https://cookiecutter.readthedocs.io/en/1.7.2/advanced/suppressing_prompts.html) in the docs.

Basically I want to be able to send in `extra_context` *that may not contain **all** of the context*, and prompt the user for the remaining.

Let's say I have this defaults file:

```json
# cookiecutter.json
{
  "author": "Me",
  "email": "",
  "project_name": ""
}
```

#### Current Behavior:

`extra_context` overrides the default values from `cookiecutter.json`. `no_input` suppresses **all** prompts.

```python
from cookiecutter.main import cookiecutter
extra_context = {"email": "foo@bar.com"}
cookiecutter(
    'cookiecutter-django',
    extra_context=extra_context,
    no_input=True,
)
```

Cookiecutter ends up using these values:

```
# Final values:
author: "Me"            # from cookiecutter.json
email: "foo@bar.com"    # from extra_context
project_name: ""        # from cookiecutter.json
```

If we do not include `no_input`, then cookiecutter will prompt for all 3 items and simply adjust their defaults:

```
# Prompts
author [me]:            # from cookiecutter.json
email [foo@bar.com]:    # from extra_context
project_name []:        # from cookiecutter.json
```

The user presses enter for all 3 prompts and we end up with the same final values as above.

#### Desired Behavior

With an option that **only prompts for values if the default value is the empty string `""`** or `None` or or `False`-y, we'd have:

```python
cookiecutter(
    'cookiecutter-django',
    extra_context=extra_context,
    input_only_for_falsey_default_values=True,     # fake, terrible api for example purposes
)
```

Cookiecutter would not prompt for `author` or `email` because they're `True`-y, and would only prompt for `project_name`:

```
# Prompts
project_name []:        # from cookiecutter.json
```

The final values used would be:

```
# Final values:
author: "Me"            # from cookiecutter.json
email: "foo@bar.com"    # from extra_context
project_name: ""        # from user prompt
```

**N.B.:** There are most likely issues with using the empty string, None, or falsey things to check. Perhaps an additional arg would be required:

```python
cookiecutter(
    'cookiecutter-django',
    extra_context=extra_context,
    input_only_for_falsey_default_values=True,     # fake, terrible api for example purposes
    prompt_if_default_is=[None, ""],         # if the default value (from cookiecutter.json or extra_context)
                                             # is in this list, then prompt the user for a value.
)
```

In fact, with `prompt_if_default_is`, `input_only_for_falsey_default_values` wouldn't be needed at all as it's implied.

### What I've run:

N/A. This is a question / feature request.

**Comment by edesz** [comment]
Hi @dougthor42, one way to achieve this is to use a pre-gen hook and update the `cookiecutter` context there (i.e. inside the hook) to add in **all** the keys that should not prompt the user for an input.

Meanwhile, those inputs that should generate a prompt will be placed in `cookiecutter.json`.

So, the hook would be `hooks/pre_gen_project.py`
```
"""{{ cookiecutter.update({"author": "Me", "email": "foo@bar.com"}) }}"""
```
which contains `author` (which you had in `cookiecutter.json`) and `email` (which was in the `extra_context`). Neither of these will generate a prompt.

The `cookiecutter.json` file only contains a single entry
```
{
    "project_name": ""
}
```
which will prompt for input.

Essentially, `extra_context` and `cookiecutter.json` have been combined into the hook - both are hard-coded and don't generate a prompt. `cookiecutter.json` now only contains `project_name`, which will prompt for and accept input.

With this, here's a sample directory structure to demo this
```bash
$ cd cookiecutter-django
$ tree

├── cookiecutter.json
├── {{cookiecutter.project_name}}
│   └── mytestfile.md
└── hooks
    └── pre_gen_project.py
```

The contents of `{{cookiecutter.project_name}}/mytestfile.md` are
```
This file is created by user={{cookiecutter.author}}, with email={{cookiecutter.email}}.

This file belongs to the project with name={{cookiecutter.project_name}}.
```

When this template is run using
```bash
$ cd ..

$ ls -l
total 12345
########-#  4 <username> <username>   #### ### ## ##:## cookiecutter-django

$ cookiecutter cookiecutter-django
```

it gives the following prompt for the only variable in `cookiecutter.json`
```bash
# Prompts
project_name []: 
```

If `mydemoproject` is entered as the project name
```
project_name []: mydemoproject
```

then `mydemoproject/mytestfile.md` is generated, which contains the following
```
This file is created by user=Me, with email=foo@bar.com.

This file belongs to the project with name=mydemoproject.
```

**Notes**
1. This is not exactly what you wanted, since the variables have been re-arranged relative to your layout. If you have some other reason to maintain the exact structure you showed (eg. to preserve some other necessary functionality in the `extra_context`, which is being entirely omitted here), then this approach won't work.
2. Additional key-value pairs that should not prompt for input should **also** be placed in the hook (since you're now into `jinja` territory, this could get messy if you have a large number of these). Meanwhile all key-value pairs that should not prompt for an input should be placed in `cookiecutter.json`.

Hope this helps.

Relevant github issues
1. [#1012 (comment)](https://github.com/cookiecutter/cookiecutter/issues/1012#issuecomment-347663602)
2. [#1115 (comment)](https://github.com/cookiecutter/cookiecutter/issues/1115#issuecomment-678760755)

**Comment by dougthor42** [comment]
Hey @edesz, thanks a bunch for that write up! I think the pre-gen hook method will be sufficient for my needs.
