### ISSUE TITLE
Fix Codeclimate in PR

### ISSUE THREAD

**Issue by SharpEdgeMarshall** [cookiecutter/cookiecutter#1523]
* Cookiecutter version:

### Description:

ATM we are passing CC_TEST_REPORTER_ID from a Github Actions secret, this is not available in PR so we are not evaluating code.

**Comment by simobasso** [comment]
@SharpEdgeMarshall, thanks for reporting this one.

As turned out in https://github.com/cookiecutter/cookiecutter/pull/1521#discussion_r616635923 and from any ci for a pull request, the `CC_TEST_REPORTER_ID` is exposed as a GitHub secret.

In GitHub Action, secrets are only exposed on ci from a branch of the same repo and not in pull requests (to avoid secrets disclosure).

As stated in the [codeclimate documentation](https://docs.codeclimate.com/docs/finding-your-test-coverage-token#should-i-keep-my-test-reporter-id-secret):

> Your repo's test coverage ID is only used to identify your repo when submitting test coverage payloads. It can't be used to access any of your data.

So I can assume that is not a secret at all.

I'll proceed to add this env var inn minutes, I hope in a review from you :)

**Comment by simobasso** [comment]
@SharpEdgeMarshall @glumia, we should decide it before I push the pr. What do you think about it?

**Comment by glumia** [comment]
> @SharpEdgeMarshall @glumia, we should decide it before I push the pr. What do you think about it?

The codeclimate documentation looks pretty clear about this ID not being sensitive information, at worst a malicious actor could send fake coverage reports for the project. 

I did some research and it looks like a common issue on Github projects that use a fork based workflow (https://github.com/rootstrap/rails_api_base/issues/264, https://github.com/lostisland/faraday/issues/984), unfortunately without a real solution.

We have to choose whether we want to expose ourselves to the risk of fake uploads and have codeclimate checks on PRs or not.

Imho we can proceed by exposing it, if we notice that someone is doing nasty things with it we can always regenerate the ID and make it secret again.

**Comment by glumia** [comment]
Yeah, I like that! At the end of the day codeclimate doesn't look that useful to me (but I could be biased, I don't know that service very well). 

+1 for adding bandit and safety: the first one to pre-commit's config, the other one ideally only on the CI.

My concern about adding safety to pre-commit is that contributors could be prevented from sending patches: if any of our dependencies get a vulnerability people could not even create commits anymore. Yes, this can be worked around using git's `--no-verify` option, but it would raise a bit the entry barrier. Safety should run only on CIs so that maintainers can eventually take care of fixing vulnerable dependencies. If we decide to add it to pre-commit then we should at least take care to mention this issue and its workaround in our `CONTRIBUTING.md` so that people can open pull requests anyway.

**Comment by simobasso** [comment]
IMHO fail fast fail often, because it's not funny spent hours of works to find out on the ci that you should wait for the fix AND that you should rebase your pr after, it's unfair.

On the other hand, security comes firsts even before the developer/user experience, especially if you have a tool like pyup where the only thing you need is to review an update made by a bot.

We can try to add safety in pre-commit, and let's see. In the worst case, we can remove the check with a pr. What do you think?

**Comment by glumia** [comment]
I think the problem remains that, in the worst-case scenario of a security vulnerability on a dependency, we are raising the entry barrier to new/inexperienced contributors. 

E.g. I'm a cookiecutter user and while at work I notice that there's an issue in the documentation (outdated information, typos, whatever). I'm not a Python developer, but at the end of the day I arrive at home and armed with good intentions I go through `CONTRIBUTING.md`, fork the project, clone the repository and start working on it. After a while I'm done so I finally try to commit my changes and... I discover I'm not able to do so because a program called 'safety' complains about a security vulnerability. Two things can happen at this point:
1. I have *a lot* of good intentions and go through the hassle of updating the vulnerable dependency (assuming there's already a new version not affected by it...) even if I don't know anything about how Python's dependencies work.
2. *"Fuck it, it's not worth it"* - I delete the repository and close my pc.

Yes, if  2. happens probably it means that those changes weren't that important, but that's a missed opportunity to get a new contributor on board.

**Comment by simobasso** [comment]
Thanks for your thoughts,

let's try with safety only in ci 👍
