### ISSUE TITLE
Help maintaining cookiecutter?

### ISSUE THREAD

**Issue by samj1912** [cookiecutter/cookiecutter#1536]
This is a continuation of the discussion at https://github.com/cookiecutter/cookiecutter/pull/1485#issuecomment-812668296

It would be nice to have an active set of maintainers for cookiecutter.

I see that @simobasso is already doing a fabulous job, but I assume there would need to be atleast a pair of active maintainers (so that maintainers can review each others PRs). If needed, I would love to help out with the maintainance. Here's my background - 

> https://github.com/cookiecutter/cookiecutter/pull/1485#issuecomment-818231393
> @HappyEinara thanks for the shout out!
> 
> @pydanny I would be more than happy to help out with the maintanance of cookiecutter (I currently maintain http://cruft.github.io/ and https://github.com/samj1912/cookies which heavily rely on cookiecutter internals so I am fairly familiar with the codebase) but I would imagine we would still need more people (at least 1 more active maintainer) to be able to go through the current backlog of PRs and issues.

LMK if I can help out in any way.

**Comment by samj1912** [comment]
cc: @cookiecutter

**Comment by simobasso** [comment]
Hey @samj1912, thanks for this issue.

As you can see, there are a lot of issues and pr to be reviewed 😅 , so if you have some little time to dedicate, feel free to contribute in the way you prefer; any help is really appreciated. 

There are also @glumia and @SharpEdgeMarshall that have some spare time to donate.

If you ask for permission, you should talk directly with @audreyfeldroy or @pydanny because even if I'm a member of the organization, I would prefer that the original authors make this kind of decisions.

**Comment by insspb** [comment]
@simobasso I do not see you in cookicutter slack or in my skype, please establish contact -> @ashpak

@samj1912 @simobasso Answers shows situation as it is. After all things happened in past year i will be glad to see new developer here. I will browse issues in next 2-5 weeks and look on your code and reviews. And in in this time nobody from original authors will not answer to you, I will make direct access myself, without such permission. 
Hope it is ok to you.

Closing this one, as answered.

**Comment by insspb** [comment]
@simobasso @samj1912 5 weeks, 1 year... What a difference. Anyway I am looking on template inheritance right now. Again thank you for contribution and patience.
