### ISSUE TITLE
Rename branch master to main?

### ISSUE THREAD

**Issue by jensens** [cookiecutter/cookiecutter#1735]
I thinks it is time. 
Are there any valid opinions against this?

**Comment by insspb** [comment]
Another one strange proposal. 
So you want all users who have for example CI/CD to rewrite their CI/CD for what reason? Any new functions with this change? Any project wide benefits?

**Comment by insspb** [comment]
@att14 

- This project was always far away from politics/trends and I am insist that this philosophy should be continued. Today you want main, tomorrow you will want gretta, day after you will want to name it ilon. Such changes does not bring any new features.
- Problem not in renaming internally. Problem is that this project used by thousands of people, and historically releases here happen not very often. that's why many usage use master directly.
- You cannot delete history of slaves exist just by renaming branches. And you never should forget a people history, to not re-make same mistakes.

**Comment by att14** [comment]
These are all completely insensitive view points; however, I did not make my comment to convince you of anything. I knew that would be futile.

> * This project was always far away from politics/trends and I am insist that this philosophy should be continued. Today you want main, tomorrow you will want gretta, day after you will want to name it ilon. Such changes does not bring any new features.


> * Problem not in renaming internally. Problem is that this project used by thousands of people, and historically releases here happen not very often. that's why many usage use master directly.
> * You cannot delete history of slaves exist just by renaming branches. And you never should forget a people history, to not re-make same mistakes.

**Comment by insspb** [comment]
@att14 When I hear 'inclusive' I remember how @jensens say the same about moving documentation to new standard of 1 sentence per line. He said that this is to be 'inclusive' and make a translations...

And what a result? 

- 0 translations attempts
- Conflict inside team, leading to 0 active developers. But we have at least 1 inclusive admin.

Ok. 'inclusive' is good. Let be inclusive. Lets change icon to rainbow. Make a documentation design in green weed relaxing style. Let's rename master to obama. Be inclusive!

Absurd. 

@att14 you even do not understand what I am talking about on changes. Just imagine that there is project 'template.x.x.'

- This imagined project has own Ci/CD, that points to our master as last version. So their CI/CD will be broken. All pull requests to such project after our rename will fail. Good job!
- Imagine that another project use as on API level and pointing to master in setup.py or requirement.txt. Hello new pull requests, new project deployments etc. 

So yes. Let's trigger insane wave of changes.

Why we need to repeat other's mistakes?

**Comment by att14** [comment]
It's easy enough to leave the existing `master` branch as is and make the default branch `main`. Then make an announcement that if anyone uses `git` to download instead of `pip` they need to switch to `main` to get future updates.

Again, the changes are really quite simple, you are just making them complicated because you would rather not accept that others have different views than you.

**Comment by insspb** [comment]
@att14 I am mainly admin, and I already faced deploy triggered by such changes in one of dependencies.

ok let's imagine. We release next version 2.1.x or 2.x.x and make an announcement that in 3.x.x we will rename master to main. But at what point we should archive master and make main default? We do not have strict roadmaps....

**Comment by att14** [comment]
Once again, this is an incredibly simple problem that you are making a big deal about. Put in the announcement that folks have 6 months to change or any arbitrary amount of time. I don't personally care. Then delete master branch after 6 months, or never delete it. Who cares.

**Comment by insspb** [comment]
@att14 For me name is not a problem. The name is problem for you. And you do not care that fixing your problem will affect other. Who cares? At the end yours problem is solved,  you make another repo 'inclusive'. Who care that many people will need to react on this.

**Comment by att14** [comment]
I think your opposition to such a simple thing is evidence enough of why this project is not inclusive and healthily growing. Regardless of the default branch's name. I will not be responding again.

**Comment by jensens** [comment]
According to out code of conduct, which is the PyPA code of conduct which is the PSF code of conduct (yes) we should rename the branch.

**Comment by insspb** [comment]
I rechecked how git works with such rename issues right now. It automatically redirects blob links isuues etc, so it is not a big problem. 
The problem will be only with pip install repo@master, but it is actually not very often used, usually only commit number or just a link specified. 
But anyway there are some manual changes that should be made:

1. Update our side CI/CD jobs to use main instead master
2. Update links inside our project if anywhere 'master' used. 
3. Update read the docs config (probably)
4. Rename branch
5. Recheck all external tools catched 'default' branch name change.

Of course there is no 178 others issues, so we need to take an effort, and rename default branch! be inclusive! Solve real problem :)

**Comment by pydanny** [comment]
This isn't up for debate. Locking discussion because we're wasting time talking about it. Some notes:

- Fixing this low hanging fruit puts us in alignment with our code of conduct
- The founder of this project is a woman of minority status (Asian) in the country she resides (USA) who also happens to be a founder of pyladies. I can assure you she prefers `main` over `master`

**Comment by jensens** [comment]
I renamed the branch. Please update your local environments.
