### ISSUE TITLE
Better hook behavior/error handling on Windows

### ISSUE THREAD

**Issue by audreyfeldroy** [cookiecutter/cookiecutter#178]
If a hook is a shell script ending in .sh, on Windows it should probably be skipped and an error message should be printed. e.g. "Cannot run post-generate hook post_gen_project.sh on Windows."

Not 100% sure if this should be the behavior on Windows. Is there a way to run .sh shell scripts on Windows? I tried in a Cygwin bash shell, but it doesn't seem possible.

Likewise, I suppose Cookiecutter should print an error instead of running a .bat hook on POSIX-compliant systems.

**Comment by pauliyobo** [comment]
I have to propose 2 things.
1.  The funtion valid_hook() in hooks.py:26, could be modified.
If the operative system does not match the right script extension, that is, if for instance you are using windows and the extension is .bat,  we could just make it an invalid hook. In that way though the hook will not be threated as such.
2. Before the hook is actually ran an error could be raised if the operative system is trying to run a script with the wrong extension.
Are those proposals any good? If yes, which one would be better?
I'm asking this because I am not sure if the intention is to notify the user, or just ignore and proceed with the execution.
