### ISSUE TITLE
Custom jinja2 extensions

### ISSUE THREAD

**Issue by RobbertDM** [cookiecutter/cookiecutter#1827]
* Cookiecutter version: 2.1.1
* Template project url: (private)
* Python version: 3.10.6
* Operating System: Ubuntu 22.04

### Description:

Hey there, I found the following docs:
https://github.com/con-f-use/cookiecutter/blob/master/docs/advanced/template_extensions.rst

 Note that these docs are not from this repository, and they're different from 
* https://cookiecutter.readthedocs.io/en/2.1.1/advanced/template_extensions.html or 
* https://github.com/cookiecutter/cookiecutter/blob/main/docs/advanced/template_extensions.rst)

Nevertheless, they do describe an interesting feature, namely the possibility to add custom jinja2 extensions to a cookiecutter template.
I followed the tutorial in the link above, made an `extensions` dir and wrote a custom jinja2 extension in a `myext.py` file.
However, I was not able to get this working, it results in a `Unable to load extension: No module named 'myext'`.

Are these custom extensions something that's built-in into cookiecutter? Is it cookiecutter's goal to support it?

Kind regards!
Robbert

PS: This person seems to be looking for it as well: https://stackoverflow.com/questions/29953348/how-to-add-a-custom-filter-for-use-in-a-cookiecutter-template

**Comment by RobbertDM** [comment]
Ah, I see it exists in the documentation already at https://cookiecutter.readthedocs.io/en/latest/advanced/local_extensions.html

**Comment by jantari** [comment]
@RobbertDM Did you get the local extensions feature to work?

Whenever I try I get: `Error message: 'env_lookup' is undefined`

My files:

### cat local_extensions.py
```python
from jinja2.ext import Extension

import os

class FoobarExtension(Extension):
    def __init__(self, environment):
        super(FoobarExtension, self).__init__(environment)
        environment.filters['env_lookup'] = lambda v: os.getenv(v)
```

### cat cookiecutter.json
```json
{
  "platform_name": "example-platform",
  "platform_owner": "{{ env_lookup('USER', 'USER') }}"
}
```

using Cookiecutter 2.1.1. Thanks!

**Comment by RobbertDM** [comment]
Cool! Thanks! No, I didn't find your `environment.globals.update(env_lookup = lambda v: os.getenv(v))` magic and just rewrote my stuff with (very ugly) built-in jinja.

**Comment by t-payne** [comment]
I was running into a similar issue as @jantari. I was trying to use the `simple_filter` decorator as described in the [Local Extensions](https://cookiecutter.readthedocs.io/en/stable/advanced/local_extensions.html) section of the docs. While debugging I realized that I was trying to use the filter as a global function (e.g. `{{ my_simple_filter(myarg) }}`) rather than a filter (e.g. `{{ myarg | my_simple_filter }}`). The Jinja [Environment](https://jinja.palletsprojects.com/en/3.0.x/api/#jinja2.Environment) has the attributes [globals](https://jinja.palletsprojects.com/en/3.0.x/api/#jinja2.Environment.globals), [filters](https://jinja.palletsprojects.com/en/3.0.x/api/#jinja2.Environment.filters), and [tests](https://jinja.palletsprojects.com/en/3.0.x/api/#jinja2.Environment.tests) (all `dict`s). So, depending on what kind of extension you are adding to the Jinja Environment, you have to add it to the right dict.

I created a simple cookiecutter template to test adding extensions to each:

#### Cookiecutter template structure
```
my-extension-template
├── cookiecutter.json
├── local_extensions.py
└── {{cookiecutter.directory_name}}
    └── myfile.yml
```

#### cookiecutter.json
```json
{
    "directory_name": "test-extensions",
    "my_num": 4,
    "my_val": "Hello",
    "_extensions": [
        "local_extensions.my_simple_filter",
        "local_extensions.MyFilterExtension",
        "local_extensions.MyGlobalExtension",
        "local_extensions.MyTestExtension"
    ]
}
```

#### local_extensions.py
```python
from cookiecutter.utils import simple_filter
from jinja2.ext import Extension


@simple_filter
def my_simple_filter(n):
    return n * 2


class MyFilterExtension(Extension):
    def __init__(self, environment):
        super().__init__(environment)

        def my_filter_extension(n):
            return int(n) ** 2

        environment.filters.update(my_filter_extension=my_filter_extension)


class MyGlobalExtension(Extension):
    def __init__(self, environment):
        super().__init__(environment)

        def my_global_extension(value="[nothing]"):
            return f"Global function called with {value}"

        environment.globals.update(my_global_extension=my_global_extension)


class MyTestExtension(Extension):
    def __init__(self, environment):
        super().__init__(environment)

        def is_truthy(n):
            return bool(n)

        environment.tests.update(truthy=is_truthy)
```

#### myfile.yml
```yaml
values:
  - {{ cookiecutter.my_num | my_simple_filter }}
  - {{ cookiecutter.my_num | my_filter_extension }}
  - "{{ my_global_extension() }}"
  - {% if cookiecutter.my_val is truthy  %}true{% else %}false{% endif %}
```
