### ISSUE TITLE
Installing a template without manually copying it 

### ISSUE THREAD

**Issue by Stefanhg** [cookiecutter/cookiecutter#1979]
* Cookiecutter version: 2.4.0
* Template project url:  None
* Python version: 3.10
* Operating System: Windows 10

### Description:

I want to be able to install a template in some way without manually copying them. 
Is this something that has been considered before? I tried to look though the GitHub but with no result.

**Concept 1**: 
I think it could be done in a simple way. 
Run: cookiecutter install (path)
Detect if it is a valid template
copy (path) to .cookiecutters directory

**Concept 2**: 
I think the optimal way to do it would be in some way do like PyTest detects plugins and detect them using an entry-point. That means it works just like a normal Python package where you just install it and then it works.
I don't know exactly how it works under the hood but It does seem possible.

**Comment by ericof** [comment]
Hello @Stefanhg, Could you please elaborate on the benefits of installing the cookiecutters locally?

**Comment by Stefanhg** [comment]
Hello @ericof 

There are a few good things about it being installable:

- Easier to install and use
- Better/easier control of which version you have installed
- More of a Pythonic way of using the cookie cutter templates
- Less code to handle Windows/Linux/MacOS/Others support

I can't come up with more good reasons for now. But since it is a Python package I think it is more pythonic to be able to install a package rather than copying it to a folder so the package can import it from it's own folder.

**Comment by alanverresen** [comment]
@Stefanhg As far as I know, you can already do everything that you've described:

- to fetch a remote cookiecutter [1,2]  
  `$ cookiecutter https://github.com/audreyfeldroy/cookiecutter-pypackage.git`
- you can also use a path to a local directory:
  `$ cookiecutter /path/to/my/cookiecutter-pypackage`

When you fetch a cookiecutter, it is installed/stored locally, as described in [3]. So, after fetching a cookiecutter for the first time, you can use it through its name to generate a project:

- `$ cookiecutter cookiecutter-pypackage`

If you want to use a specific older version of a cookiecutter using version control, you can typically link a specific commit. Turning cookiecutters into packages would only result in extra work without adding any benefits, and I would actually disagree with every "good thing" that you listed.

That being said, I've noticed that there is no option/flag to "fetch a cookiecutter, but don't generate a new project right now". I think it would be handy if an `--install-only` or `--fetch-only` flag was available, so that people can "install" cookiecutters without immediately having to use them.

[1] https://cookiecutter.readthedocs.io/en/latest/README.html#for-users-of-existing-templates
[2] https://cookiecutter.readthedocs.io/en/latest/usage.html#works-directly-with-git-and-hg-mercurial-repos-too
[3] https://cookiecutter.readthedocs.io/en/latest/usage.html#keeping-your-cookiecutters-organized
