### ISSUE TITLE
Plugin/extension system

### ISSUE THREAD

**Issue by audreyfeldroy** [cookiecutter/cookiecutter#59]
Make it possible to implement Cookiecutter plugins like:
- @pydanny's secret key plugin and similar
- a basic input validation plugin that can be extended or swapped out (see https://github.com/audreyr/cookiecutter-pypackage/issues/6)

This issue is dependent on #29 / #48.

I wonder if there would be a way to implement the plugin system such that #55 would be possible as a plugin. Not sure.

**Comment by brettcannon** [comment]
I have somewhat run into a need for this as I have a template with some repeated, complicated Jinja templating that I don't want to make into one explicit Jinja plugin that people have to depend on so as to not gain a dependency on my template. It would be great if from some hook I could directly manipulate the Jinja context to inject my own items and plugins.

**Comment by hackebrot** [comment]
Hi @brettcannon! 👋 

Would your "own items and plugins" have any dependencies (other than what is already required by cookiecutter itself)?

**Comment by brettcannon** [comment]
Nope. Honestly I just want a way to add more items programmatically after the user has entered their info.

To put this in concrete terms, I'm doing `{{ cookiecutter.python_version|replace('.', '')|truncate(2, end='') }}` across two files in multiple places (setting a variable when I can, but I'm still doing it multiple files), so I would rather do that manipulation in my pre-hook in Python code and store the result in the `cookiecutter` object so I could then access it from the Jinja code. So no dependencies at all since it's just straight-forward string manipulation that would be easier in Python than Jinja.

**Comment by hackebrot** [comment]
Okay, cool. 🙇 

I've used [jinja2 assignments](http://jinja.pocoo.org/docs/dev/templates/#assignments) to help with that, but as you say, it doesn't work across multiple files.

Thanks for the feedback, I'll take it into consideration when we design a plugin system.

**Comment by hackebrot** [comment]
I think this falls under the same category as #848. Assigning the **Requires Sponsorship** label until we have sponsorship for this project.

**Comment by kurtmckee** [comment]
@jensens @pydanny @ssbarnea This issue is 10 years old. I recommend closing the issue.
