### ISSUE TITLE
Revert appveyor architecture tests

### ISSUE THREAD

**Issue by hackebrot** [cookiecutter/cookiecutter#615]
Since tox does not distinguish between different architectures by default (we figured that out just recently in a different project), I feel it makes sense to reduce our CI times... :worried: 

Tox has its own way of determining the python interpreter, which means even if you create the virtual environment with a x64 version, tox uses x86 on appveyor internally.

Let's revert #567 

cc @maiksensi

**Comment by maiksensi** [comment]
Actually, I would rather add another small patch to the current config to make sure that tox uses the correct interpreter internally. The lookup mechanism (on Windows at least) is to look at the `PATH` and if there is a python interpreter, it uses that one. So in order to use the correct interpreter, we would need to set the `PATH` variable in `appveyor.yml`. 

I would like to test this before reverting the changes. 
--> todo would be: 
* look up how tox determines the interpreter
* create a test repo with appveyor support and test the interpreter with a test

**Comment by hackebrot** [comment]
Cool, whatever works best :+1: 

As of right now, I'd rather not wait for appveyor to finish if the tests are redundant.

**Comment by maiksensi** [comment]
then revert the changes and I'll put up a new PR when I get to it.

**Comment by insspb** [comment]
We are dropping appveyor. Closing issue.
