### ISSUE TITLE
Remove YAML as a supported format

### ISSUE THREAD

**Issue by pydanny** [cookiecutter/cookiecutter#743]
# Justification

Cookiecutter uses YAML for parsing the `.cookiecutterrc` config file. Otherwise, the library relies on JSON for configuration (and anything that runs as a hook). This means it affects a tiny portion of the project, but it has caused an a number of issues for the project:
- pyYAML doesn't work everywhere
- Ruamel.YAML doesn't work everywhere
- Poyo works everywhere, but the Debian community has decided to patch Cookiecutter rather than include it (they already have a Python-based YAML parser). Whether or not I agree with their decision I can understand their position. I can also see how other distributors would raise the same issue.
- Since you can call the `main.cookiecutter()` with `extra_context`, **there is nothing stopping anyone from writing a simple wrapper that calls `main.cookiecutter()` and injects those values into the context**.

Some intangible issues:
- Having now observed hundreds using the tool and having never seen `.cookiecutterc` used by anyone, it is my theory that usage of `.cookiecutterrc` is incredibly limited. In other words, we're supporting just a select few.
- @hackebrot has spent and continues to spend time on Poyo. I can't speak on his behalf, but I prefer to watch him work creatively on Cookiecutter core, py.test, pytest cookies, etc rather than a YAML edge case. This isn't meant to trivialize his work, on the contrary! Having seen his creativity in action I want to see more of it.

Which leads me to summarize that the Cookiecutter community is using an inordinate amount of energy to support YAML for a tiny audience when JSON or even a custom wrapper module suffices for the rest of us. 

For those who want to continue to support YAML for things, perhaps HJSON is an acceptable alternative. Either by importing their library natively or by simply stripping `# comments` from JSON cookiecutter.json modules before we load them into Python.
# Methodology

Considering the limited impact of `.cookiecutterrc` and YAML on the code base, this should be relatively straightforward to implement in a single pull request. That said, I think we should keep it in the next release, albeit with a warning message that links to documentation providing an example of how to write a mitigation wrapper around Cookiecutter.

**Comment by audreyr** [comment]
I use `.cookiecutterrc`, @pydanny 😜 

We can just print an error message when a YAML `.cookiecutterrc` is found. Then they can update their config to .ini or whatever new config format we support for it.

**Comment by pydanny** [comment]
Okay, besides @audreyr I've never seen anyone else use this feature. I think switching it to JSON is fine.

**Comment by vaab** [comment]
My 2 cents. Thanks for sharing your decisions first. A little sorry to see what I consider a bad choice to be taken, but this is a choice. And this is better than keeping dangling PR without any explanation for years.

I would have been happier if this thread would have summarized or linked the actual problems that you have faced. I had to google the problem with debian to get more information about this topic. I don't know what mean "xxx doesn't work everywhere" ... and I would rather have seen "xxx doesn't work on ...".
Debian thread on this topic is clearer and there choice seems much saner, and this "poyo" introduction is a great example how direction of ``cookiecutter`` can seem immature to my eyes from times to times.

What I had to recollect is that YAML is not the culprit, but indirectly, implementations that exists suffers from issues of the python packaging system (correct me if I'm wrong, I inferred this through reading the debian issue - https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=823200 , which is much more informative BTW).
However it seems that a *lot* of well-known project rely on pyyaml (according to the Debian discussions). You seem to push your requirement bar higher than these project, and higher than what python packaging is able to reach... and this is NOT a surprise : python packaging is a complete wreckage, done again and again.
However, PyYAML always seem to be installable after some relatively small ad-hoc manual fiddling, and was tackled by all major distribution.

About your communication (first post of this issue), please don't say that you don't know anyone using YAML for cookiecutterrc ... we don't need generalization here, but looking to closed PRs seems to show you have selective blindness (I'm not claiming that we are many thou, nor I know how many we represent). In general, I receive your information post as abused generalization, incomplete information, unreferenced affirmation and all seems baked information in favor of your decision, this is not helping having a clear understanding of your justification, or pushing myself to buy in most of your affirmations. Please take this as a simple feedback of how your annoucement could be taken, and feel free to ignore it or a source for improving your communication. Links towards PRs dealing with these issues you had with pyyaml (and others), Links towards the debian decision you are referring to. 

Despite all this, I think I understood your intention and general message : It seems that you have a goal that is not stated clearly of **being very easily installable on all your supported platform through the last python packaging installers**. And, in that perspective, PyYAML generated way too much effort to meet these requirements due to poor state of python packaging system in combination with this package, so this pushed you to consider the possibility to go without YAML, and as a matter of fact, YAML capability has a small footprint and does not seem to be used that much from your experience, and alternative language seem legit here also so you choose to move away from PyYAML.

I'm very aware that I probably missed crucial points of information about this story. Feel free to add. My main point here is that if you want to document properly your decision for posterity and newcomers, it lacks proper information and references.

**Comment by willingc** [comment]
@pydanny clearly explains the decision to remove YAML support. A [quick search of GitHub](https://github.com/search?q=.cookiecutterrc&ref=searchresults&type=Code&utf8=%E2%9C%93) shows that use of YAML in ``.cookiecutterrc`` is tiny.

Thanks for choosing a technical direction that works without manual intervention by template users to address operating system nuances. 👍

**Comment by pydanny** [comment]
Hey @vaab, I'm at the airport, so here are some quick notes (some which reinforce what you suggest):

* https://github.com/audreyr/cookiecutter/issues?q=is%3Aissue+yaml+is%3Aclosed displays several reference tickets to the YAML issue. 
* The problem has arguably nothing to do with Python, but rather the portability of C code written for PyYAML and Ruamel.YAML. If those libraries can't write and maintain cross-platform C code, then Cookiecutter just can't use them.
* Cookiecutter aims to support all users across all platforms. We've attempted to patch in different YAML parsers depending on the target operating systems, but that turned out to be more work then it was worth. It's incredibly challenging and time consuming to test all operating systems and their variants (Linux, OSX, Windows).
* It needs to be said that we don't want to treat any other operating system or variant unfairly. Examples:
  * **Debian**: We feel it is unfair of us to force @vincentbernat to have to patch Cookiecutter so he can do us the service of packaging it on Debian.
  * **Windows**: Through no decision of their own, a lot of Cookiecutter's users are on Windows. Forcing them to jump through challenging hurdles (getting YAML libraries to compile) to use our software is not fair.

Our goals could be stated as:

* We want a very easily installable library on all major operating systems
* We want a very easily maintained library (after all, we are unpaid volunteers)
* We would rather focus on stability and API improvements then dealing with getting YAML working everywhere.

**Comment by vincentbernat** [comment]
I am perfectly OK with patching Cookiecutter for Debian. The patch is quite small and it is less work for me than maintaining another YAML library. However, you (upstream) may feel uncomfortable with having Cookiecutter patched this way.

**Comment by pydanny** [comment]
@vincentbernat We would rather have the same library everywhere, as that makes diagnosing issues reported by users easier for us. Plus, less work for you! 😁

**Comment by pydanny** [comment]
Here's a super-simple script showing how to override the defaults using Cookiecutter:

``` python
from cookiecutter.main import cookiecutter

cookiecutter(
    template_name='.',
    extra_context={
        "project_name": "Hello, World",
        "author_name": "Daniel Roy Greenfeld"
    }
)
```

Adding in YAML support might be something like this:

``` python
import io

from cookiecutter.main import cookiecutter
import yaml

with io.open("~/.cookiecutterrc", encoding='utf-8') as f:
    raw = f.read()
    cookiecutter(
        template_name='.',
        extra_context=yaml.safe_load(raw)
    )
```

Or... you could just write a script using bash that passes in `extra_context` as an argument. There are so many ways to add in your own YAML support.

**Comment by vaab** [comment]
@pydanny: thanks for the technical details and information, I think they have their place in this thread for curious and technical people.

Your quick URL listing issues might have been a little quickly done: I have only found 1 issue related to this topic (number #557). This issue is somewhat informative: it is about replacing pyyaml with ruamel, and that PyYAML is thought to be not maintained anymore on python 3.5 on windows, Ruamel.YAML being presented as a maintained fork of PyYAML. 
Sorry if I missed something obvious.

And thanks for your sample code... this is pertinent here.

**Comment by hackebrot** [comment]
@willingc I’m afraid a search on GitHub is not representative for how many users actually use cookiecutterrc, since it lives in a user’s home directory and is not necessarily referred to from code outside of cookiecutter itself

@pydanny Thank you. 🙇

I also use the feature and do think some form of it should be kept. I find it really handy - mostly for the default context variable.

How to configure cookiecutters_dir and replay_dir w/o the config file? This is a problem IMHO and must be taken into consideration. Obviously this can also be achieved with a json/hjson format.

@vaab Some examples for problems resulting from PyYAML or ruamel.yaml:
- https://github.com/audreyr/cookiecutter/pull/558 win 7 pyyaml
- https://github.com/audreyr/cookiecutter/issues/569 ubuntu ruamel.yaml
- [ruamel/yaml/issues/14](https://bitbucket.org/ruamel/yaml/issues/14/cant-install-ruamelyaml-package-under) win 7 and win 8 ruamel.yaml
- [audreyr/cookiecutter/build/1.0.996](https://ci.appveyor.com/project/audreyr/cookiecutter/build/1.0.996) broken appveyor builds with codecov using pyyaml

@vincentbernat Thank you for your continued support for Cookiecutter on Debian. I don’t like to the fact that there is a distribution of Cookiecutter that differs from master for various reasons. Mostly because it adds an unnecessary level of complexity. I am not familiar with the Debian packaging guidelines, but I feel there is a [misunderstanding](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=823200#10) around the [Poyo](https://github.com/hackebrot/poyo) project and it’s scope.

To briefly explain [why I created Poyo](https://github.com/hackebrot/poyo/commit/8ff701ff58542a1d72a0ff40b1b50ae41df42a6d#diff-88b99bb28683bd5b7e3a204826ead112R76) in the first place:

There are two nearly identical Python YAML parsers on PyPI that seem to be difficult to install on various platforms and/or Python versions. 

Latest PyYAML release 2014-03-27. Last commit 2014-11-28. One person with access to PyPI package.
- https://pypi.python.org/pypi/PyYAML
- https://bitbucket.org/xi/pyyaml

Latest ruamel.yaml release 2016-05-12. Last commit 2016-05-02. One person with access to PyPI package.
- https://pypi.python.org/pypi/ruamel.yaml 
- https://bitbucket.org/ruamel/yaml

The reason I mention theses dates and the number of authors is because it allows assumptions on how well maintained a project is. The YAML specification is very complex and I find it impressive that aforementioned libraries support most of the features. However there seem to be recurring problems with installations, particularly on Windows but also on other popular platforms. **Cookiecutter depends on these libraries and failed attempts to install YAML parsers mean that users can’t install Cookiecutter. This is really bad!**

The cookiecutter [user config](
https://github.com/audreyr/cookiecutter/blob/master/cookiecutter/config.py) file supports 4 variables, 2 of which are simple key/value variables and the other 2 are a flat dict:

```yml
default_context:
    full_name: "Foo Bar"
    email: "foo@bar.com"
    github_username: "foobar"
abbreviations:
    cookiedozer: https://github.com/hackebrot/cookiedozer.git
    gh: https://github.com/{0}.git
cookiecutters_dir: ~/.cookiecutters/
replay_dir: ~/.cookiecutter_replay/
```

A cookiecutter user config only requires a subset of the YAML spec and that’s where Poyo comes in. Yes, it supports only a chosen subset of the YAML format and is not compatible with JSON, but it solves a critical problem for Cookiecutter w/o breaking backwards compatibility. As a maintainer of both Cookiecutter and Poyo I do have a great interest in keeping both projects healthy.

All in all I don’t see a reason to depend on fully-fledged Python YAML parsers, especially when they cause all sorts of trouble during installation for a feature that not everyone uses. I wonder if anyone would have noticed if we didn’t decide to create a separate package for it. It’s 430 lines of code including doc strings with a 79 character per line limit. :wink:

Hope this sheds some light on why there is yet another “YAML Parser for Python”.

**Comment by vincentbernat** [comment]
I understand why Poyo exists. However, in Debian, I have to package separately each dependency. So, I have to package Poyo while we already have two perfectly working and complete YAML parser. There is no installation problems for us with them as we provide working packages for them.

Packages are screened before inclusion in Debian and adding a third Python package that only parses a subset of YAML will likely rise some eyebrows, notably if the alternative is a simple patch. Moreover, an additional package is more effort.

The question is just: is it OK to have a patch for Debian/Ubuntu or, as upstream, do you strongly prefer to stick with Poyo. In the later case, I'll package it and see what happens.

**Comment by vaab** [comment]
@hackebrot thanks for the collection of issues. 

- #569 is about python-dev required, which is required for any python package having C dependencies... Did you really intend to includ this for a motivation of removal of PyYAML ?
- #558 is not super informative, I only can infer that something doesn't work on windows 7 and python 3.5, only. Is this the issue that triggered all your reflexions about PyYAML being maintained or not ?... Even then, it's probably much better to patch PyYAML (or ruamel) (this could be handy for a whole bunch of projects out there depending on pyyaml). To be honest, this will probably be the way all major distribution will go when they'll face this issue as the patch to make it work is probably very small as it concern only a combination of python version and platform, and keeping in mind that you can always fallback to full python parsing if there's a real issue hiding there, preventing the compilation.

I'm kinda inclined towards the debian frowning: subset of languages are harmfull... I'm pretty happy that each small project do not create their own limited version of a parser for their own needs. 

It seems it might have been much more costly to implement this package than to make a regular patch to cover what seem a very restricted issue in PyYAML.

@pydanny Another missing reference I would have appreciated in your first post: Is PyYAML abandonned ? (thread on the last official tracking issue): https://bitbucket.org/xi/pyyaml/issues/59/has-this-project-been-abandoned#comment-27477700

**Comment by pydanny** [comment]
@vaab, this is your first and last warning about [Code of Conduct](https://github.com/audreyr/cookiecutter#code-of-conduct) violations against regular contributors to Cookiecutter. The item of the Code of Conduct you are specifically violating is:

* [Trolling or insulting/derogatory comments](https://www.pypa.io/en/latest/code-of-conduct/#contributor-code-of-conduct)

A sample of your insulting/derogatory writing (which has been screen captured) from this comment thread:

* "And this is better than keeping dangling PR without any explanation for years."
* "and this "poyo" introduction is a great example how direction of cookiecutter can seem immature to my eyes from times to times"
* "which is much more informative BTW"
* "Did you really intend to includ this for a motivation of removal of PyYAML?"

Any future violations will result in an immediate banning from this project. While we encourage debate, we refuse to condone this kind of ongoing abusive behavior. We wouldn't allow this kind of treatment as paid employees, and we certainly won't take it as volunteers for an unpaid project.

**Comment by pydanny** [comment]
@vincentbernat The use of YAML in Cookiecutter is incredibly minor, and used merely for configuration of a single file. Using `configparser` would serve the same purpose, and would drop the package size of Cookiecutter immensely since it would work off assuredly cross-compliant stdlb Python code.

Therefore, after all this discussion I've decided that even if PyYAML were patched (the maintainer has moved on, something I completely respect), even if Poyo on Debian weren't an issue, this removal of YAML from the project would still retain merit.

**Comment by vaab** [comment]
@pydanny I acknowledge hereby your warning, and decide as a consequence to remove myself of this discussion.
I apologize to any people offended by my remarks or behavior.
I understand that I won't be able to help you in anyway here in the current environment.
I wish this project the very best. Kudos for the developpers of this package that I'll be continuing to use from afar.
And sorry for the spam, this exchange should not have been done in this thread.

**Comment by ssbarnea** [comment]
I am closing this because most of the reasons for creating this long time ago are no longer valid, pyyaml is actively maintained.  Sad that this thread resulted in loosing at least one contributor. 

It is kinda fun that after 3 years I face myself asking a similar question: what to do when one of your dependencies is not maintained? This ticket was about `cookiecutter->pyyaml` and now I have another issue [`molecule->cookeicutter`](https://github.com/ansible/molecule/issues/2102) where a decision would need to be done. Fixing upstream dependencies is almost always the best approach, when possible.
